search_space:
  delta:
    _type: choice
    _value: [ 0.5, 1, 2, 5, 10 ]

trial_command: python main_non_contextual.py --nni --method ExploreThenExploitA --num-prod 50 -s 0.5
trial_code_directory: ..

trial_concurrency: 5
max_trial_number: 5

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
